name: blue_cash
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7


  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/image/
    - assets/icon/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ThinItalic.ttf

    - family: Oleo_Script
      fonts:
        - asset: assets/fonts/Oleo_Script/OleoScript-Bold.ttf
        - asset: assets/fonts/Oleo_Script/OleoScript-Regular.ttf

    - family: Work_Sans
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-VariableFont_wght.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-Black.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-BlackItalic.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-Bold.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-BoldItalic.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-ExtraLightItalic.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-Italic.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-Light.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-LightItalic.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-Medium.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-MediumItalic.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-Regular.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-SemiBold.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-SemiBoldItalic.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-Thin.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-ThinItalic.ttf