// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCKe-0D1Io0dO0O7FwLX_hD-WFLrVmUP4',
    appId: '1:212220895347:web:12f588b904dbf232dd0a06',
    messagingSenderId: '212220895347',
    projectId: 'bluecash-7b5b4',
    authDomain: 'bluecash-7b5b4.firebaseapp.com',
    storageBucket: 'bluecash-7b5b4.firebasestorage.app',
    measurementId: 'G-JLZKYPEGBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCw8EChisyDMkbdOmTAzKHSoOYwSNfK4',
    appId: '1:212220895347:android:20fb310f058a04ecdd0a06',
    messagingSenderId: '212220895347',
    projectId: 'bluecash-7b5b4',
    storageBucket: 'bluecash-7b5b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZz9ckEUgN3CP3hdcclPzMG1Fbc03lOg',
    appId: '1:212220895347:ios:3d1150bc00265dafdd0a06',
    messagingSenderId: '212220895347',
    projectId: 'bluecash-7b5b4',
    storageBucket: 'bluecash-7b5b4.firebasestorage.app',
    iosBundleId: 'com.example.blueCash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALZz9ckEUgN3CP3hdcclPzMG1Fbc03lOg',
    appId: '1:212220895347:ios:3d1150bc00265dafdd0a06',
    messagingSenderId: '212220895347',
    projectId: 'bluecash-7b5b4',
    storageBucket: 'bluecash-7b5b4.firebasestorage.app',
    iosBundleId: 'com.example.blueCash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCKe-0D1Io0dO0O7FwLX_hD-WFLrVmUP4',
    appId: '1:212220895347:web:9c37651b5277ce80dd0a06',
    messagingSenderId: '212220895347',
    projectId: 'bluecash-7b5b4',
    authDomain: 'bluecash-7b5b4.firebaseapp.com',
    storageBucket: 'bluecash-7b5b4.firebasestorage.app',
    measurementId: 'G-QTF404T7PE',
  );

}